### ISSUE TITLE
Can't connect Streamer.bot

### ISSUE THREAD

**Issue by AudricSan** [rivafarabi/streamerbot-deckboard#2]
I can't connect streamer.Bot and Deckboard.
I'm probably not doing it correctly, but as I can't find the documentation I'm sending a message here.
Thank you very much !

![image](https://user-images.githubusercontent.com/29382102/170055440-eaa152d3-9342-4974-9acf-03dbc77c3d4a.png)

**Comment by GAMINGCHATS** [comment]
I have the same problem.

**Comment by scsa20** [comment]
Doesn't connect for me either. One thing I did found looking through the code is that it's using the HTTP Server instead of Websocket Server but even after updating the setting on deckboard to use the port for the HTTP server, it still does not connect (and yes the HTTP server is running).

**Comment by rivafarabi** [comment]
It seems you need to restart the Deckboard to properly connected to Streamer.bot. Make sure the HTTP server is already running before Deckboard does.

Will look further for this issue this weekend.

**Comment by scsa20** [comment]
OK, so I finally did got it to connect after much trial and error. One thing I saw was when trying to configure it the settings wouldn't stick until I did the address as 127.0.0.1/ (and ye I restarted deckboard after saving each time). Looked like it finally worked after I removed the slash and the IP actually stayed this time. Just weird.

**Comment by Jakub72** [comment]
Having StreamerBot and Deckboard running on the same PC seems to eventually work after it finally decides to connect with one another (using the same settings as above). However, I can't seem to get Deckboard to remotely connect to StreamerBot on a different PC in the same Local Network. Is there a fix for this?
